name: Compile and Upload Artifacts

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Compile Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code
      
    - name: Set up Go 1.22
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Compile with compile.sh
      run: |
        chmod +x ./compile.sh
        ./compile.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-software
        path: |
          ./bin/*
