name: Compile and Upload Artifacts with CGO_DISABLED

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Compile Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code
      
    - name: Set up Go 1.22
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Compile with compile_cgoless.sh
      run: |
        chmod +x ./compile_cgoless.sh
        ./compile_cgoless.sh
    
    - name: Compress all binaries
      run: |
        tar cv ./bin_cgoless | zstd -T0 -16 > bin_cgoless.tar.zst

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-software
        path: |
          ./bin_cgoless.tar.zst
